[package]
name = "rust-plugin-test"
version = "0.1.0"
edition = "2024"

[dependencies]
dragonfly-plugin = { path = "../"}
rust-plugin-macro = { path = "../rust-plugin-macro"}
tokio = { version = "1", features = ["full"] }
